### ISSUE TITLE
Does this library manage the OAUth side of things

### ISSUE THREAD

**Issue by MrSent** [tipstrade/TipsTrade-HMRC#1]
This package seems excellent from what I can tell so far. Only came across it a few days ago. One of the big issues with doing VAT returns is connecting to the HMRC gateway. Does this package provide a mechanism for dealing with the OAuth side of things?

Thanks for the effort you've gone to in doing this package.

**Comment by tipstrade** [comment]
Yes, the TipsTrade.HMRC.Client has the following methods for handling the OATH tokens:
- GetAuthorizatoinEndpoint
- HandleEndpointResult
- RefreshAccessToken

If you have a look at the Tests and Authentication-Client (namely the GetAuthCode method)  projects, you'll see how they're used. I haven't had enough time to document the methods, but they should be fairly self-documenting via the XML comments.

**Comment by MrSent** [comment]
Thanks. Yeah, this is a superb piece of work.

**Comment by tipstrade** [comment]
Thanks for the feedback, it's appreciated. I've quickly added some examples to the README, but as I said, have a look at the accompanying projects.
