### ISSUE TITLE
Not an issue really. Just an update on recent issues to say they're fixed

### ISSUE THREAD

**Issue by MrSent** [tipstrade/TipsTrade-HMRC#12]
This isn't an issue really. Just an update to say the recent issues I have have now been resolved. I altered the get obligations and the antifraud stuff. I have some info such as the device ID, the MFA unique reference, device manufacturer and model set in a config file but on first run, they're blank so I run a method to populate them. 

The device ID and MFA unique references are just Guid.NewGiud() function calls and stored so that they should never change. The device manufacturer and model were relatively easy. I added a reference to System.Management and added this code:

```c#
using (ManagementObjectSearcher searcher = new ManagementObjectSearcher(new SelectQuery(@"Select * from Win32_ComputerSystem")))
                {
                    foreach (ManagementObject process in searcher.Get())
                    {
                        process.Get();
                        appSettings.UserAgentDeviceManufacturer = process["Manufacturer"].ToString();
                        appSettings.UserAgentDeviceModel = process["Model"].ToString();
                    }
                }
```
Seems to work.

Loading the antifraud stuff and the client I did this:

```c#
            antiFraud = new AntiFraud()
            {
                ConnectionMethod = ConnectionMethod.DESKTOP_APP_DIRECT,
                DeviceID = appSettings.AntiFraudDeviceID,
                Screens = new TipsTrade.HMRC.AntiFraud.Screen[] { new TipsTrade.HMRC.AntiFraud.Screen() { ColourDepth = 32, ScalingFactor = 1, Size = new Size(1920, 1080) } },
                TimeZone = TimeZoneInfo.Local,
                VendorVersion = new Dictionary<string, string>() { { Assembly.GetExecutingAssembly().GetCustomAttributes(typeof(AssemblyDescriptionAttribute), false).OfType<AssemblyDescriptionAttribute>().FirstOrDefault().Description, Assembly.GetExecutingAssembly().GetName().Version.ToString() } },
                WindowSize = new Size(1024, 768),
                UserIDs = new Dictionary<string, string>() { { "os", Environment.UserName } }
            };

            antiFraud.PopulateLocalIPs();
            antiFraud.PopulateMACAddresses();
            antiFraud.PopulateUserAgent();

            antiFraud.UserAgent.DeviceManufacturer = appSettings.UserAgentDeviceManufacturer;
            antiFraud.UserAgent.DeviceModel = appSettings.UserAgentDeviceModel;

            antiFraud.MultiFactor = new[]
            {
                new MultiFactor()
                {
                    Method = MFAMethod.AUTH_CODE,
                    TimeStamp = DateTime.Now,
                    UniqueReference = appSettings.MFAUniqueReference
                }
            };

            client.ClientID = sClientId;
            client.ClientSecret = sClientSecret;
            client.ServerToken = sServerToken;
            client.AntiFraud = antiFraud;
```

When getting obligations, I was having problems with an invalid date range. The documentation says all the query parameters are optional but if you omit them all, you get an error, so they're not all optional. I don't add the status in the request, but for the date range, I used this:

```c#
        private void PopulateDateRange(IDateRange value)
        {
            int iYear = DateTime.Now.Year;
            int iMonth = DateTime.Now.Month;

            value.DateTo = new DateTime(iYear, iMonth, DateTime.DaysInMonth(iYear, iMonth));
            value.DateFrom = value.DateTo.AddYears(-1).AddDays(1);
        }
```
Tried it on the sandbox and things were fine. Tried it on a live system and after re-granting of authority, I could successfully get obligations again, and it didn't complain about the antifraud, so all seems to be good.

Thanks for looking into stuff and sorting. You've been more help than HMRC have been!

**Comment by tipstrade** [comment]
Thanks for posting that. It's really helpful when people post how they got things working 👍 There's nothing more frustrating than someone posting _"fixed it"_ with no other comments.

> When getting obligations, I was having problems with an invalid date range.

Yup, they're really picky about date ranges, as you've found out they're not actually optional, and also throws an error when getting a to large a date range (you've gone for exactly the same solution as I did). That bit me in the ass as I had an off-by-one error so I was requesting 367 days for making requests after March 1st as it was a leap year...

> You've been more help than HMRC have been!

I really appreciate that, thanks. Although you seem to have worked out most of it yourself!

**Comment by MrSent** [comment]
> That bit me in the ass as I had an off-by-one error so I was requesting 367 days for making requests after March 1st as it was a leap year...

Haha, yeah I got that one. It threw me completely because I thought the range I'm getting was 366 days as handily this year is a leap year otherwise I wouldn't have noticed until 2024! The date range is apparently inclusive, so picking the 366 days as a range gave me 367 actual days which I thought I'd fix by doing .AddDays(1-) and it stopped complaining.
