### ISSUE TITLE
Weird response on VAT submission

### ISSUE THREAD

**Issue by MrSent** [tipstrade/TipsTrade-HMRC#13]
I have an error response which I am getting when submitting a VAT return which is this:

```
<error>
  <Code>invalid_grant</Code>
  <Message>refresh_token is invalid</Message>
  <ErrorPath />
</error>
```
I assume the code and message are taken straight from the response from HMRC? I've searched HMRC's code and your code, and I've been through their documentation, and nowhere lists this error message. Any ideas?

**Comment by MrSent** [comment]
Hmm, it's mentioned here https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints without much description

**Comment by tipstrade** [comment]
Is this in the sandbox environment or the production?

According to [RFC 6749](https://tools.ietf.org/html/rfc6749#section-5.2), invalid_grant means

> The provided authorization grant (e.g., authorization
> code, resource owner credentials) or refresh token is
> invalid, expired, revoked, does not match the redirection
> URI used in the authorization request, or was issued to
> another client.

Like you say, it's not a great help. It can't be that it's expired as the HMRC docs say that `invalid_request` is thrown if the token has expired.

I have to admit that I find that the refresh token is rarely accepted after not being used for a couple of months (which for quarterly VAT returns is fairly usual) even though the token is supposed to expire after 18 months. So users tend to have to reauthenticate, which is annoying but only has to happen ever 3 months.  **Edit: I've put it down to HMRC invalidating my tokens for an unknown reason, but I ~~could~~ am probably wrong about that and have been ignoring the real cause**

I'll dig out a log of what was thrown for the last person that has had this happen.

**Comment by MrSent** [comment]
It's their live system. They have finally admitted it's a live service issue. They are so slow at dealing with issues and I end up wasting so much time investigating problem that are their doing. Thanks again for looking.

**Comment by tipstrade** [comment]
That's good to hear (from my point of view). Did they explain what the issue is that is causing this, and do they have an estimate of when it'll be fixed?

**Comment by MrSent** [comment]
I don't think they know at this time. The exact response today was:

"...
This is a Live Service Issue we are currently aware of and are trying to fix as a priority.
Apologies for the problems you are facing, we will be in touch as soon as a fix is identified.
..."

**Comment by tipstrade** [comment]
> This is a Live Service Issue we are currently aware of and are trying to fix as a priority.
> Apologies for the problems you are facing, we will be in touch as soon as a fix is identified.

That's about as vague as I should have expected from a UK government department...
