### ISSUE TITLE
Token Response problem

### ISSUE THREAD

**Issue by MrSent** [tipstrade/TipsTrade-HMRC#16]
I've got an issue that seems to have arisen recently. When calling client.HandleEndpointResult or client.RefreshAccessToken I am getting an error which comes back as "Object reference not set to an instance of an object."

The logs output I have shows this:
1. 07/12/2020 17:41:58:- Calling refresh on the client.RefreshAccessToken('f8b7xx65d846f496cbdccfdc028719xx')
2. 07/12/2020 17:41:58:- General exception caught
3. 07/12/2020 17:41:58:- Object reference not set to an instance of an object.
4. 07/12/2020 17:41:58:- TipsTrade-HMRC
5. 07/12/2020 17:41:58:- 
6. 07/12/2020 17:41:58:- System.Collections.ListDictionaryInternal
7. 07/12/2020 17:41:58:-    at TipsTrade.HMRC.Api.Model.ErrorResponse.FromOAuth2Error(String json)
   at TipsTrade.HMRC.Client.RefreshAccessToken(String refreshToken)
   at MTD3.FrmACLHMRCAuth.GetNewAccessAndRefreshTokens(Client client) in C:\Users\XXXXXX\Documents\XXXXXXX\Code\MTD\Project\MTD\MTD\FrmACLHMRCAuth.cs:line 594

I have 2 catches in my code:

```c#
                catch (ApiException ex)
                {
                    HandleLogRequest("Going to call ConstructApiError");
                    ConstructApiError(ex); // Calls a function to write the error out
                }
                catch (Exception ex)
                {
                    HandleLogRequest("General exception caught");
                    // stuff happens here
                }
```

The problem is that the ApiException is not being caught. It drops into the Exception and all that gives is the log output above. Line 3 is Message, 4 is the Source, 5 is the InnerException, 6 is the Data and 7 is the StackTrace.

Nothing has changed in my code for month but now anything that calls a method that returns a token response is causing an error. Any help on this would be greatly appreciated.

**Comment by tipstrade** [comment]
I'll look into this.

**Comment by tipstrade** [comment]
Can you explain what each of the following log lines are from. The final line is obviously the stacktrace, but I'm I don't know what the `System.Collections.ListDictionaryInternal` is referring to.

I can't reproduce the error here, even if I send an invalid refresh token. The only reason I can think of is if the JSON being returned is an empty string. I still don't know where `System.Collections.ListDictionaryInternal` is coming from though.

- `07/12/2020 17:41:58:- Object reference not set to an instance of an object.`
  I guess this is the ex.Message
- `TipsTrade-HMRC`
  Assembly?
- `07/12/2020 17:41:58:-`
  Is this supposed to be a blank line, or is it outputting a property that happens to be empty.
- `07/12/2020 17:41:58:- System.Collections.ListDictionaryInternal`
  Is this an inner exception message?

**Comment by MrSent** [comment]
The object reference is the ex.message. The TipsTrade-HMRC is the ex.source, the blank one is the ex.innerexception and the last one I thought I'd just dump out ex.data to see what was there.

I have a feeling when I am constructing the client, I am not populating the correct access and refresh tokens so when I call client.HandleEndpointResult or client.RefreshAccessToken I am getting an exception as the values aren't there. I am just trying to verify that.

**Comment by tipstrade** [comment]
> the last one I thought I'd just dump out ex.data to see what was there.

Ah, that makes sense now. I can now reproduce this if I pass either an empty string, or a string literal `"null"` to `ErrorResponse.FromOAuth2Error`, although the only way I can reproduce this bug reliably is to disable my network connection so the response is empty. Could this be the root cause of your issue?

I've noticed that unlike in the APIs, I'm not throwing an underlying exception returned by the RestClient, so any underlying network errors were being eaten by `RefreshAccessToken` and `HandleEndpointResult`, which obviously shouldn't be happening.

**Comment by tipstrade** [comment]
I've also noticed

**Comment by MrSent** [comment]
I shall do some more testing and let you know my findings. Thanks for looking

**Comment by tipstrade** [comment]
As you can see from the commit messages, I've pushed up some fixes. I've also made sure that if an exception is contained in a RestResponse, the actual exception is thrown, rather than wrapping it inside of an ApiException. This way you can catch and indentify issues like network errors separately.

**Comment by MrSent** [comment]
This is the error I am getting now:

General error: The request was aborted: Could not create SSL/TLS secure channel. I'm aware that HMRC have stopped allowing TLS 1.0 and 1.1 now. I use an HTTPListener to manage the connection.

**Comment by MrSent** [comment]
Ahh. The app is built on .NET 4.5.2 and the default protocol is not TLS1.2. If I built the app against .NET 4.6 it would use 1.2 as the default.

Any reason on your library side that I can't use 4.6 or above?

**Comment by MrSent** [comment]
Adding this to the MTD.exe.config file forces the TLS level to be 1.2 or later:

```xml
<configuration>
  <runtime>
    <AppContextSwitchOverrides value="Switch.System.Net.DontEnableSystemDefaultTlsVersions=false"/>
  </runtime>
</configuration>
```

Now I don't get the TLS/SSL error. I haven't rebuilt against 4.6 or above.

**Comment by MrSent** [comment]
Once I'd got that message, I altered the exe config file and that solves it. I have rebuilt my app anyway with the latest build you provided. Thanks for your help.
