### ISSUE TITLE
Authentication-Client

### ISSUE THREAD

**Issue by SugdenM** [tipstrade/TipsTrade-HMRC#17]
I have been trying to run Authentication Client provided locally and have been receiving an unauthorised result when trying to create a client from the menu.

It would appear the ServerToken has been [deprecated ](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation)by the HMRC so I am struggling to identify the changes required to get this working. All I really want to do is to use the Check-Vat-Registration number API> I was using this app to see how to di this using dotnet but have not been successful. Any advise would be greatly appreciated.

**Comment by oobayly** [comment]
I haven't had any issues using the Authentication Client to generate users. I appreciate the server token is being deprecated, and will have a look into this.

I wasn't even aware that they'd added a Check VAT Number API. I'll look into adding this, but I'm afraid time is fairly scarce for me at the moment.
