### ISSUE TITLE
Using scopes

### ISSUE THREAD

**Issue by MrSent** [tipstrade/TipsTrade-HMRC#2]
I've got a full OAuth journey completed now using the examples you provided. Thanks for those. I have a question on the scopes. As I'm really only interested in read:vat and write:vat and not really interested in hello, when calling the scopes method the code has this line:

var scopes = Scopes.GetScopes()

Is there a way I can specify the scopes I want to use so I can just request read and write without hello? I don't mind if hello has to be there but from a cleanness point of view, when the customer logs into the gateway to grant authority to the application, can I return an array with the two in it instead of the one? I read the code in the package but I couldn't work it out.

**Comment by tipstrade** [comment]
The Scopes.GetScopes method is overloaded. You can use a generic overload to get all the scopes for a specific API
```C#
var scopes = Scopes.GetScopes<Api.Vat.VatApi>();
```
or  you can pass the optional valueFilter and nameFilter arguments:
```C#
// All Scopes in the Scopes class that contains "VAT", eg. "VATRead", "VATWrite"
var scopes = Scopes.GetScopes(nameFilter: (name) => name.Contains("VAT"));

// All scopes in the Scopes class that are for the VAT api, and contain "read"
var scopes = Scopes.GetScopes<Api.Vat.VatApi>(valueFilter: (value) => value.Contains("read"));
```

You can of course simply select the scopes using their constants too.

**Comment by MrSent** [comment]
When doing an obligations request I populate the request and return an obligation response. When I try that it gives me an error "The VAT (MTD) API requires Anti Fraud headers."

Having read about these which are currently not mandatory, it suggests I put them in. Well, I'd rather put them in now and get them right rather than suddenly have to work it out later. I just can't seem to get it right.

`
            antiFraud = new TipsTrade.HMRC.AntiFraud.AntiFraud()
            {
                ConnectionMethod = TipsTrade.HMRC.AntiFraud.ConnectionMethod.DESKTOP_APP_VIA_SERVER,
                DeviceID = $"{Guid.NewGuid()}",
                TimeZone = TimeZoneInfo.Local,
                VendorVersion = new System.Collections.Generic.Dictionary<string, string>() { { Assembly.GetExecutingAssembly().GetCustomAttributes(typeof(AssemblyDescriptionAttribute), false).OfType<AssemblyDescriptionAttribute>().FirstOrDefault().Description, Assembly.GetExecutingAssembly().GetName().Version.ToString() } }
            };
`
In your code I can see the anti fraud test which suggests that I should then call the following functions:

`
            antiFraud.PopulateLocalIPs();
            antiFraud.PopulateMACAddresses();
            antiFraud.PopulateScreens();
            antiFraud.PopulateUserAgent();
`
This populates everything I need, but then I can't go any further because there are other things that aren't populated. It says that PublicAddress can't be empty. Calling the PopulateLocalIPs does fill the LocalIPs property with all IPs on the system, but what do I set in the PublicAddress and how do I set it? What about the port? I'm launching from a desktop application.

**Comment by tipstrade** [comment]
I've added documentation about Scopes
