### ISSUE TITLE
Setting anti fraud headers

### ISSUE THREAD

**Issue by MrSent** [tipstrade/TipsTrade-HMRC#3]
When doing an obligations request I populate the request and return an obligation response. When I try that it gives me an error "The VAT (MTD) API requires Anti Fraud headers."

Having read about these which are currently not mandatory, it suggests I put them in. Well, I'd rather put them in now and get them right rather than suddenly have to work it out later. I just can't seem to get it right.

`antiFraud = new TipsTrade.HMRC.AntiFraud.AntiFraud() { ConnectionMethod = TipsTrade.HMRC.AntiFraud.ConnectionMethod.DESKTOP_APP_VIA_SERVER, DeviceID = $"{Guid.NewGuid()}", TimeZone = TimeZoneInfo.Local, VendorVersion = new System.Collections.Generic.Dictionary<string, string>() { { Assembly.GetExecutingAssembly().GetCustomAttributes(typeof(AssemblyDescriptionAttribute), false).OfType<AssemblyDescriptionAttribute>().FirstOrDefault().Description, Assembly.GetExecutingAssembly().GetName().Version.ToString() } } };`
In your code I can see the anti fraud test which suggests that I should then call the following functions:

`antiFraud.PopulateLocalIPs(); antiFraud.PopulateMACAddresses(); antiFraud.PopulateScreens(); antiFraud.PopulateUserAgent();`
This populates everything I need, but then I can't go any further because there are other things that aren't populated. It says that PublicAddress can't be empty. Calling the PopulateLocalIPs does fill the LocalIPs property with all IPs on the system, but what do I set in the PublicAddress and how do I set it? What about the port? I'm launching from a desktop application.

**Comment by tipstrade** [comment]
I think you should be using DESKTOP_APP_DIRECT - that method doesn't need the public IP. DESKTOP_APP_VIA_SERVER would be used when the intermediate server is the on making the API requests

> Installed desktop application connecting through intermediary servers to HMRC

See the Header contents section of the [Fraud Prevention](https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention) documentation for which case the methods would be used.

The Populate* methods are just helper methods. It's entirely up to you the developer to know which ConnectionMethod is most applicable to your use, what values are needed for each anti fraud header, and how they are collected.

**Comment by MrSent** [comment]
Thanks. I'll try that. Regarding the helper methods I'll use them to populate the collections and do the rest myself :)

Much appreciated.
