### ISSUE TITLE
Obligations date range

### ISSUE THREAD

**Issue by MrSent** [tipstrade/TipsTrade-HMRC#5]
When requesting the obligations, HMRC shows in their endpoints that the from and to dates are optional. If I omit them from the obligations request entirely I would expect to just get all obligations but I get INVALID_DATE_RANGE. If I want to get all obligations, regardless of status, how can I do that? I see you use a function to populate the date ranges within each of the requests and this covers a range within the last quarter.

**Comment by tipstrade** [comment]
They're sort of optional (which IMO isn't ideal):

> Date from which to return obligations. Mandatory unless the status is O.

So you'll still need a date range if you're trying to get all obligations. I have however made sure not to pass the from and to values to the API if they're `default(DateTime)`. I can't confirm it, but I **assume** that requesting only Open obligations will return a single result, but until I test it out of the sandbox I can't be sure.

I'll be pushin out a new release which fixes that issue, but it does contain some [breaking changes](https://github.com/tipstrade/TipsTrade-HMRC#breaking-changes)

**Comment by MrSent** [comment]
Thanks for the heads up on the breaking changes. I can live with that. Ok, I get the dates being sort of optional. That sucks. I'll deal with it my own way in that case

**Comment by oobayly** [comment]
Just to confirm, the new version will allow you to omit the date range when retrieving Open obligations.

Even more frustrating is that you will get an INVALID_DATE_RANGE error if you specify a date range of more than a year. I'm not sure if this limit will apply in production. During a chat with one of the HMRC team, it was mentioned that as much as they'd like the sanbox to replicate the exact behaviour of the production environment, it doesn't, so we have to make do with the foibles.

Edit: I've noticed that the 12 Feb 2019 changelog mentions that they made the date range optional.

> You are now able to retrieve open obligations without supplying a from and to date range. You can simply supply status=O and you will receive all open obligations.
