### ISSUE TITLE
Gove Test Scenario missing from Vat Submit

### ISSUE THREAD

**Issue by MrSent** [tipstrade/TipsTrade-HMRC#6]
In the VAT Submission there is a test scenario missing and one that shouldn't be there. According the HMRC the VAT submission test scenarios are:
INVALID_VRN
INVALID_PERIODKEY
INVALID_PAYLOAD
DUPLICATE_SUBMISSION
TAX_PERIOD_NOT_ENDED

Your API includes:
INVALID_ARN

And doesn't provide:
TAX_PERIOD_NOT_ENDED

**Comment by oobayly** [comment]
Ah thanks, I'll get them implemented. That was originally written in November 2018, and I guess they've changed the scenarios (~~I'm pretty sure I wouldn't have invented INVALID_ARN~~ The removed INVALID_ARN in January). They joys of subscribing to a Beta API!
